name: angularUnitTest
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Node.js ${{ matrix.node-version }}
      - run: |
          cd ${{ github.workspace}}/site/"interface web"/frontendInterfaceWeb
          npm ci
      - name: Use Node.js ${{ matrix.node-version }}
      - run: |
        cd ${{ github.workspace}}/site/"interface web"/frontendInterfaceWeb
        npm run test:prod