name: Integration tests (jest)
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies + launch jest integration tests
      run: |
        cd ${{ github.workspace}}/site/"interface web"/backend
          npm install
          npm run test